export PATH=/usr/local/bin:$PATH
export GEM_HOME=$HOME/.gem/
MQTT_HOST=mqtt.piscada
MYSQLSHELL=/usr/local/mysql/bin
PATH=$HOME/bin:/usr/local/bin:$PATH:$MQTT_HOST
CLASSPATH=$packages:$MYSQLSHELL:$MQTT_HOST
alias xcode='open -a /Applications/Xcode.app'
export MYSQLSHELL
export PATH
export CLASSPATH
export MQTT_HOST
alias i="cd ~/iCloud/com~apple~CloudDocs/Documents"
export PATH="$HOME/.cargo/bin:$PATH"
